[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  # Allow @netlify/plugin-nextjs to run so Next.js features like image optimization work.

[[plugins]]
  package = "@netlify/plugin-nextjs"